### ISSUE TITLE
docker/{mongo,common-services}.yml missing volumes for persistent services

### ISSUE THREAD

**Issue by grooverdan** [Microsoft/ghcrawler#134]
As far as I can tell the mongodb, redis and rabbitmq docker compose images would benefit from persistent volumes to save a large (re)initialisation time if they are restarted.

Seems easy to add:
https://docs.docker.com/compose/compose-file/#volumes

Volumes required:

mongodb: /data/db /data/configdb
ref: https://github.com/docker-library/mongo/blob/master/3.6/Dockerfile#L85

redis: /data
ref: https://github.com/docker-library/redis/blob/master/4.0/Dockerfile#L70

rabbitmq:  /var/lib/rabbitmq
ref: https://github.com/docker-library/rabbitmq/blob/master/3.7/debian/Dockerfile#L132

metabase: /var/opt/metabase/
from: metabase/Dockerfile

**Comment by jeffmcaffer** [comment]
I do recall conversations around using persistent volumes but to not recall the reasoning. @iamwillbar might know. In theory I don't see a problem.

**Comment by iamwillbar** [comment]
This makes sense, `metabase` declares a volume but I can't recall why we didn't for the others.
