### ISSUE TITLE
Implement Table based mapping store

### ISSUE THREAD

**Issue by geneh** [Microsoft/ghcrawler#62]
Test performance of URL to URN mapping with Azure table implementation vs. Redis.

**Comment by geneh** [comment]
https://github.com/Microsoft/ghcrawler/pull/66

**Comment by geneh** [comment]
This issue is going to be opened until the mapping store is completely migrated from Redis to Azure table.

**Comment by jeffmcaffer** [comment]
this is deployed to prod.  Thanks @geneh !
