### ISSUE TITLE
CAIB: turn on persistence 

### ISSUE THREAD

**Issue by jeffmcaffer** [Microsoft/ghcrawler#64]
Mongo, rabbit and redis need persistence turned on in the container world (or at least an option to do so)

* consider not turning it on for redis.  in the mongo case we are not storing the url and urn mapping in redis.  The queue contents are tracked in redis but if we lose that, it is not fatal.

**Comment by willbar** [comment]
MongoDB container was already persisting the data directory. I added persistence for Metabase.
